# Generated by Django 5.1.1 on 2024-09-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matric_no',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
